/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from '@react-three/fiber'

import { useGLTF } from '@react-three/drei'

import useGameState from '../hooks/useGameState'

export default function Model(props) {
  const car = useRef()
  const { nodes, materials } = useGLTF(
    '/models/car.gltf'
  )
  const controls = useGameState(state => state.controls)
  const [carPos, setCarPos] = useState({ position: { x: 0, y: -2.5, z: 0 }, rotation: { x: 0, y: Math.PI, z: 0 } })

  useFrame(({ mouse }) => {
    if ((controls.left && controls.right) || (!controls.left && !controls.right)) {
      setCarPos(prev => ({
        position: { ...prev.position, x: prev.position.x > 0 ? prev.position.x -= 0.01 : prev.position.x < 0 ? prev.position.x += 0.01 : 0 },
        rotation: {
          ...prev.rotation,
          x: prev.rotation.x > 0 ? prev.rotation.x -= 0.01 : 0,
          y: prev.rotation.y > Math.PI ? prev.rotation.y -= 0.01 : prev.rotation.y < Math.PI ? prev.rotation.y += 0.01 : Math.PI,
          z: prev.rotation.z > 0 ? prev.rotation.z -= 0.01 : prev.rotation.z < 0 ? prev.rotation.z += 0.01 : 0
        }
      }))
    }

    if ((controls.left && !controls.right)) {
      setCarPos(prev => ({
        position: { ...prev.position, x: Math.max(-0.5, prev.position.x -= 0.01) },
        rotation: {
          ...prev.rotation,
          x: Math.min(0.1, prev.rotation.x += 0.01),
          y: Math.min(Math.PI + 0.5, prev.rotation.y += 0.01),
          z: Math.max(-0.3, prev.rotation.z -= 0.01)
        }
      }))
    }

    if ((!controls.left && controls.right)) {
      setCarPos(prev => ({
        position: { ...prev.position, x: Math.min(0.5, prev.position.x += 0.01) },
        rotation: {
          ...prev.rotation,
          x: Math.min(0.1, prev.rotation.x += 0.01),
          y: Math.max(Math.PI - 0.5, prev.rotation.y -= 0.01),
          z: Math.min(0.3, prev.rotation.z += 0.01)
        }
      }))
    }

    // setCarPos(prev => ({
    //   position: { ...prev.position, x: mouse.x * 6 },
    //   rotation: {
    //     z: +mouse.x * 0.5,
    //     x: mouse.x >= 0 ? mouse.x * 0.5 : -mouse.x * 0.5,
    //     y: Math.PI - mouse.x * 1.1
    //   }
    // }))
  })

  useFrame(() => {
    car.current.rotation.x = carPos.rotation.x
    car.current.rotation.y = carPos.rotation.y
    car.current.rotation.z = carPos.rotation.z
    car.current.position.x = carPos.position.x
    car.current.position.y = carPos.position.y
    car.current.position.z = carPos.position.z
  })

  return (
    <group ref={car} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_body013.geometry} material={materials['plastic.001']} />
      <mesh geometry={nodes.Mesh_body013_1.geometry} material={materials['paintGreen.001']} />
      <mesh geometry={nodes.Mesh_body013_2.geometry} material={materials['lightFront.001']} />
      <mesh geometry={nodes.Mesh_body013_3.geometry} material={materials['_defaultMat.001']} />
      <mesh geometry={nodes.Mesh_body013_4.geometry} material={materials['window.001']} />
      <mesh geometry={nodes.Mesh_body013_5.geometry} material={materials['lightBack.001']} />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft010.geometry}
        material={nodes.Mesh_wheel_frontLeft010.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft010_1.geometry}
        material={nodes.Mesh_wheel_frontLeft010_1.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft031.geometry}
        material={nodes.Mesh_wheel_frontLeft031.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft031_1.geometry}
        material={nodes.Mesh_wheel_frontLeft031_1.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft032.geometry}
        material={nodes.Mesh_wheel_frontLeft032.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft032_1.geometry}
        material={nodes.Mesh_wheel_frontLeft032_1.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft009.geometry}
        material={nodes.Mesh_wheel_frontLeft009.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft009_1.geometry}
        material={nodes.Mesh_wheel_frontLeft009_1.material}
      />
    </group>
  )
}

useGLTF.preload(
  '/models/car.gltf'
)




